AWSTemplateFormatVersion: '2010-09-09'
Description: "Full WAFv2 protection: SQLi, XSS, Common, Rate Limiting, Captcha"

Resources:
  WebACL:
    Type: AWS::WAFv2::WebACL
    Properties:
      Name: wayber-full-waf
      Scope: REGIONAL
      DefaultAction:
        Allow: {}
      VisibilityConfig:
        SampledRequestsEnabled: true
        CloudWatchMetricsEnabled: true
        MetricName: wayber-full-waf-metrics
      Description: "WAFv2 Web ACL for ALB with managed rules, rate limiting, and CAPTCHA"
      Rules:
        - Name: AWSManagedCommonRuleSet
          Priority: 0
          OverrideAction:
            None: {}
          Statement:
            ManagedRuleGroupStatement:
              VendorName: AWS
              Name: AWSManagedRulesCommonRuleSet
          VisibilityConfig:
            SampledRequestsEnabled: true
            CloudWatchMetricsEnabled: true
            MetricName: CommonRuleSet

        - Name: AWSManagedSQLiRuleSet
          Priority: 1
          OverrideAction:
            None: {}
          Statement:
            ManagedRuleGroupStatement:
              VendorName: AWS
              Name: AWSManagedRulesSQLiRuleSet
          VisibilityConfig:
            SampledRequestsEnabled: true
            CloudWatchMetricsEnabled: true
            MetricName: SQLiRuleSet

        - Name: RateLimitRule
          Priority: 3
          Action:
            Block: {}
          Statement:
            RateBasedStatement:
              Limit: 1000
              AggregateKeyType: IP
          VisibilityConfig:
            SampledRequestsEnabled: true
            CloudWatchMetricsEnabled: true
            MetricName: RateLimitRule

        - Name: CaptchaLoginSignup
          Priority: 4
          Action:
            Captcha: {}
          Statement:
            OrStatement:
              Statements:
                - ByteMatchStatement:
                    FieldToMatch:
                      UriPath: {}
                    PositionalConstraint: STARTS_WITH
                    SearchString: "/login"
                    TextTransformations:
                      - Priority: 0
                        Type: NONE
                - ByteMatchStatement:
                    FieldToMatch:
                      UriPath: {}
                    PositionalConstraint: STARTS_WITH
                    SearchString: "/signup"
                    TextTransformations:
                      - Priority: 0
                        Type: NONE
          VisibilityConfig:
            SampledRequestsEnabled: true
            CloudWatchMetricsEnabled: true
            MetricName: CaptchaLoginSignup

Outputs:
  WebACLArn:
    Description: ARN of the WAFv2 Web ACL
    Value: !GetAtt WebACL.Arn

  WebACLId:
    Description: ID of the WAFv2 Web ACL
    Value: !GetAtt WebACL.Id
